// Code generated by mfd-generator v0.5.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type TaskSearch struct {
	search

	ID        *int
	UserTgID  *int
	Priority  *int
	Length    *int
	Deadline  *time.Time
	CreatedAt *time.Time
	StartAt   *time.Time
	StatusID  *int
	IDs       []int
}

func (ts *TaskSearch) Apply(query *orm.Query) *orm.Query {
	if ts == nil {
		return query
	}
	if ts.ID != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.ID, ts.ID)
	}
	if ts.UserTgID != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.UserTgID, ts.UserTgID)
	}
	if ts.Priority != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Priority, ts.Priority)
	}
	if ts.Length != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Length, ts.Length)
	}
	if ts.Deadline != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Deadline, ts.Deadline)
	}
	if ts.CreatedAt != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.CreatedAt, ts.CreatedAt)
	}
	if ts.StartAt != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.StartAt, ts.StartAt)
	}
	if ts.StatusID != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.StatusID, ts.StatusID)
	}
	if len(ts.IDs) > 0 {
		Filter{Columns.Task.ID, ts.IDs, SearchTypeArray, false}.Apply(query)
	}

	ts.apply(query)

	return query
}

func (ts *TaskSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ts == nil {
			return query, nil
		}
		return ts.Apply(query), nil
	}
}

type UserSearch struct {
	search

	ID       *int
	StatusID *int
	IDs      []int
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.StatusID != nil {
		us.where(query, Tables.User.Alias, Columns.User.StatusID, us.StatusID)
	}
	if len(us.IDs) > 0 {
		Filter{Columns.User.ID, us.IDs, SearchTypeArray, false}.Apply(query)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}
