// Code generated by mfd-generator v0.5.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	Task struct {
		ID, UserTgID, Priority, Length, Deadline, CreatedAt, StartAt, StatusID string

		UserTg string
	}
	User struct {
		ID, TimeSlots, StatusID string
	}
}{
	Task: struct {
		ID, UserTgID, Priority, Length, Deadline, CreatedAt, StartAt, StatusID string

		UserTg string
	}{
		ID:        "taskId",
		UserTgID:  "userTgId",
		Priority:  "priority",
		Length:    "length",
		Deadline:  "deadline",
		CreatedAt: "createdAt",
		StartAt:   "startAt",
		StatusID:  "statusId",

		UserTg: "UserTg",
	},
	User: struct {
		ID, TimeSlots, StatusID string
	}{
		ID:        "tgId",
		TimeSlots: "timeSlots",
		StatusID:  "statusId",
	},
}

var Tables = struct {
	Task struct {
		Name, Alias string
	}
	User struct {
		Name, Alias string
	}
}{
	Task: struct {
		Name, Alias string
	}{
		Name:  "tasks",
		Alias: "t",
	},
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
}

type Task struct {
	tableName struct{} `pg:"tasks,alias:t,discard_unknown_columns"`

	ID        int        `pg:"taskId,pk"`
	UserTgID  *int       `pg:"userTgId"`
	Priority  int        `pg:"priority,use_zero"`
	Length    int        `pg:"length,use_zero"`
	Deadline  time.Time  `pg:"deadline,use_zero"`
	CreatedAt time.Time  `pg:"createdAt,use_zero"`
	StartAt   *time.Time `pg:"startAt"`
	StatusID  int        `pg:"statusId,use_zero"`

	UserTg *User `pg:"fk:userTgId,rel:has-one"`
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID        int           `pg:"tgId,pk"`
	TimeSlots UserTimeSlots `pg:"timeSlots,use_zero"`
	StatusID  int           `pg:"statusId,use_zero"`
}
