// Code generated by mfd-generator v0.4.5; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, Nickname, CreatedAt, StatusID string
	}
	Place struct {
		ID, PlaceName, PlacePriority, UserID, CreatedAt string

		User string
	}
}{
	User: struct {
		ID, Nickname, CreatedAt, StatusID string
	}{
		ID:        "userId",
		Nickname:  "nickname",
		CreatedAt: "createdAt",
		StatusID:  "statusId",
	},
	Place: struct {
		ID, PlaceName, PlacePriority, UserID, CreatedAt string

		User string
	}{
		ID:            "placeId",
		PlaceName:     "placeName",
		PlacePriority: "placePriority",
		UserID:        "userId",
		CreatedAt:     "createdAt",

		User: "User",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	Place struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Place: struct {
		Name, Alias string
	}{
		Name:  "places",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID        int       `pg:"userId,pk"`
	Nickname  string    `pg:"nickname,use_zero"`
	CreatedAt time.Time `pg:"createdAt,use_zero"`
	StatusID  int       `pg:"statusId,use_zero"`
}

type Place struct {
	tableName struct{} `pg:"places,alias:t,discard_unknown_columns"`

	ID            int       `pg:"placeId,pk"`
	PlaceName     string    `pg:"placeName,use_zero"`
	PlacePriority int       `pg:"placePriority,use_zero"`
	UserID        *int      `pg:"userId"`
	CreatedAt     time.Time `pg:"createdAt,use_zero"`

	User *User `pg:"fk:userId,rel:has-one"`
}
