-- =============================================================================
-- Diagram Name: gold-botsrv
-- Created on: 11/11/2025 2:31:39 AM
-- Diagram Version: 
-- =============================================================================


CREATE TABLE "users" (
	"tgId" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"timeSlots" jsonb NOT NULL,
	"statusId" int4 NOT NULL DEFAULT 1,
	PRIMARY KEY("tgId")
);

CREATE TABLE "tasks" (
	"taskId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"userTgId" int4,
	"priority" int4 NOT NULL,
	"length" int4 NOT NULL,
	"deadline" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"startAt" timestamp with time zone,
	"statusId" int4 NOT NULL DEFAULT 1,
	PRIMARY KEY("taskId")
);


ALTER TABLE "tasks" ADD CONSTRAINT "Ref_tasks_to_users" FOREIGN KEY ("userTgId")
	REFERENCES "users"("tgId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


